In [1]:
import numpy as np
import pandas as pd

In [10]:
# square vs rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2)
print(S), print(" ")
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

# diag

# trianguler
S = np.random.randn(5, 5)
U = np.triu(S)
L = np.tril(S)
print(S)
print(U)
print(L)


           

[[-0.94208971  0.22064977 -0.08985777  0.9449811   0.80923977]
 [-0.44772408  1.53982007  1.14985295 -0.23120922 -0.66941896]
 [ 0.05783117  0.23378952 -0.87994654 -0.5892941   1.20784511]
 [ 0.704134   -0.02122645  0.51317441 -2.08978808 -0.02307615]
 [ 0.9272012   1.43154378 -0.16353807 -1.35590432  0.43778613]]
 
[[-2.07781567  0.62032175]
 [ 0.08552847 -1.43720369]
 [-0.06323966  1.22664795]
 [-1.76050747  1.79728749]
 [ 0.51615277 -2.52670382]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0.52018253  0.01818096  0.10816081 -0.80276195  2.48634528]
 [-0.86192359  1.0184401   0.31564895 -1.07836086 -1.42831867]
 [-0.82495991  0.26535929  0.96684299 -0.12057941  0.31545715]
 [ 0.41635999  0.20550428 -0.82995323 -0.55454363  0.98361075]
 [-1.08960614 -0.26721072 -0.6233555  -1.5465237  -0.43761287]]
[[ 0.52018253  0.01818096  0.10816081 -0.80276195  2.48634528]
 [ 0.          1.0184401   0.31564895 -1.07836086 -1.42831867]
 [ 0. 