In [1]:
import numpy as np
import pandas as pd

In [2]:
# square vs rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2)
print(S), print(" ")
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

# diagonal
D = np.diag([1,2,3,5,2])
print(D)

# trianguler
S = np.random.randn(5, 5)
U = np.triu(S)
L = np.tril(S)
print(S)
print(U)
print(L)

#concatenate 
A = np.random.randn(3, 2)
B = np.random.randn(3, 4)
C = np.concatenate((A,B), axis = 1)

print(C)
           

[[-0.60765355  1.44800545  0.6937541   0.41982494 -0.40390922]
 [ 1.33846562  0.03301089 -1.31074385 -1.00951833  1.46594047]
 [-0.73783625 -0.16418461  0.07149667 -0.78728732 -2.5271942 ]
 [-0.99708712  1.4824481   1.52820533  1.0948925  -0.09226473]
 [-1.81636576 -0.07747032 -0.71614345 -0.13999781 -0.48755959]]
 
[[-0.08646675  0.57982333]
 [-0.23564776 -0.22698103]
 [ 0.81121408  0.34513855]
 [ 1.95709687  1.3530623 ]
 [ 0.62897095 -0.3812467 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
[[ 2.43744216  0.37837829 -0.1025147   1.06751414  1.24305944]
 [ 0.19275532  0.53514665  0.569336   -0.68975841 -0.11180472]
 [ 0.46995667  2.24789364 -0.59589422 -1.46968201  1.40107467]
 [ 2.81010762 -0.65484835 -0.11992304  1.05720395 -0.8889483 ]
 [ 0.05496833  0.09312864  0.31889592 -0.39523882  1.31562664]]
[[ 2.43744216  0.37837829 -0.1025147   1.06751414  1.24305944]
 [ 

In [3]:
A = np.random.randn(5,4)
C = np.random.randn(5,4)
A + C

#shifting
A = np.random.randn(5,5)
print(A)
A = A + 1*np.eye(5)
print(A)

[[-0.39811281  0.94794486  2.17493474 -1.75979249  0.17215532]
 [-0.51773226  0.8333872  -1.19937832 -0.6257557   0.43321273]
 [ 0.51324314  0.83035574  1.38200127  0.9483544   1.87901941]
 [ 0.8906616  -1.15766407  1.26105518 -0.11857441 -0.65276031]
 [ 0.75303826 -0.28018247 -0.06450893 -0.01831761  0.09519082]]
[[ 0.60188719  0.94794486  2.17493474 -1.75979249  0.17215532]
 [-0.51773226  1.8333872  -1.19937832 -0.6257557   0.43321273]
 [ 0.51324314  0.83035574  2.38200127  0.9483544   1.87901941]
 [ 0.8906616  -1.15766407  1.26105518  0.88142559 -0.65276031]
 [ 0.75303826 -0.28018247 -0.06450893 -0.01831761  1.09519082]]


In [4]:
M = np.array([[1,2],[2,5]])
s = 2
print(M*s)
print(s*M)

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


In [5]:
M = np.array([[1,2,3],[2,3,4]])
print(M)
print(M.T)
print(M.T.T)
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]
[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]


In [6]:
C = np.array([4 +1j,3, 2-4j])
print(C)
print(C.T)
print(np.transpose(C))
print(np.matrix(C).H) # hermitian works only this way

[4.+1.j 3.+0.j 2.-4.j]
[4.+1.j 3.+0.j 2.-4.j]
[4.+1.j 3.+0.j 2.-4.j]
[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]


In [13]:
# Diagonla and trace
M = np.round(5 * np.random.randn(4,4))
print(M)
d = np.diag(M)
print(d)
d = np.diag(M)
D = np.diag(d)
print(d)
print(D)

tr = np.trace(M)
tr2 = sum(np.diag(M))
print(tr, tr2)

[[ 9. -7.  2. -4.]
 [ 4.  2. 15. -5.]
 [ 2. -4.  3.  0.]
 [ 3.  8. -1.  3.]]
[9. 2. 3. 3.]
[9. 2. 3. 3.]
[[9. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]
17.0 17.0


In [21]:
A = np.random.randint(10, size=(3,3)) 
B = np.random.randint(10, size=(3,3))

print(np.trace(A) + np.trace(B))
print(np.trace(A + B))

print(np.trace(3*A))
print(3*np.trace(A))


24
24
36
36
