In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math

In [62]:
# compute Rank
m, n = 4, 6

# random number matrix is almost always full rank
A = np.random.randn(m, n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print(" rankg {}".format(ra))

# set last column to be repeat of penultimate column
B = A
# B[:, -1] = B[:, -2]
B[-1, :] = B[-2, :]
print(A)
print(B)
rb = np.linalg.matrix_rank(B)
print(" rankg {}".format(rb))


 rankg 4
[[-0.59478598 -0.9000241  -0.27214805  0.25014818  1.05411655  0.38431334]
 [-0.61107858 -1.84204688  0.76862682 -0.5061341   0.6543975   0.41761338]
 [-1.77691438  2.35392555  0.53564292  0.18759256  1.90401967  0.76688968]
 [-1.77691438  2.35392555  0.53564292  0.18759256  1.90401967  0.76688968]]
[[-0.59478598 -0.9000241  -0.27214805  0.25014818  1.05411655  0.38431334]
 [-0.61107858 -1.84204688  0.76862682 -0.5061341   0.6543975   0.41761338]
 [-1.77691438  2.35392555  0.53564292  0.18759256  1.90401967  0.76688968]
 [-1.77691438  2.35392555  0.53564292  0.18759256  1.90401967  0.76688968]]
 rankg 3
